version: '2'

services:
  rentit:
    image: teamrr/rentit
    ports:
      - "8090:8080"
    networks:
      - magic_network
    environment:
      POSTGRES: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: apples

  postgres:
    image: postgres
    networks:
      - magic_network
    environment:
      POSTGRES_PASSWORD: apples

networks:
  magic_network: