CREATE SEQUENCE PlantIDSequence START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE PlantReservationSequence START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE PurchaseOrderIDSequence START WITH 1 INCREMENT BY 1;
