CREATE SEQUENCE IF NOT EXISTS PlantIDSequence START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS PlantReservationSequence START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS PurchaseOrderIDSequence START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS PoExtensionIDSequence START WITH 100 INCREMENT BY 1;